module.exports = {
  apps: [
    {
      name: 'ai-dashboard',
      cwd: '/opt/ai-dashboard',
      script: 'npm',
      args: 'start',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        DB_HOST: 'localhost',
        DB_PORT: '5432',
        DB_NAME: 'ai_operations_agent',
        DB_USER: 'openclaw_user',
        DB_PASSWORD: process.env.DB_PASSWORD,
        OPENCLAW_URL: 'http://127.0.0.1:18789',
        OPENCLAW_TOKEN: process.env.OPENCLAW_TOKEN,
        OPENCLAW_HOOK_TOKEN: process.env.OPENCLAW_HOOK_TOKEN,
        VAPI_API_KEY: process.env.VAPI_API_KEY,
        VAPI_PHONE_NUMBER_ID: process.env.VAPI_PHONE_NUMBER_ID,
        VAPI_WEBHOOK_SECRET: process.env.VAPI_WEBHOOK_SECRET,
        NEXT_PUBLIC_BASE_URL: process.env.NEXT_PUBLIC_BASE_URL || 'https://gloura.me',
        OPENAI_API_KEY: process.env.OPENAI_API_KEY,
        SMTP_HOST: 'smtp.gmail.com',
        SMTP_PORT: '587',
        SMTP_USER: 'jkhancarconnect@gmail.com',
        SMTP_PASS: process.env.SMTP_PASS,
        SMTP_FROM: 'jkhancarconnect@gmail.com',
      },
      max_memory_restart: '500M',
      instances: 1,
      autorestart: true,
      watch: false,
    },
  ],
};
